name: Deploy
permissions:
  id-token: write
  contents: read
on:
  push:
    branches: 
      - main
jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: DeterminateSystems/nix-installer-action@cd46bde16ab981b0a7b2dce0574509104543276e # v9
      - uses: DeterminateSystems/magic-nix-cache-action@8a218f9e264e9c3803c9a1ee1c30d8e4ab55be63 # v2
      - uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: arn:aws:iam::686862074153:role/deploy 
          aws-region: eu-central-1
      - name: init
        run: |
          cd tf
          nix develop --command ./tofu-init.sh
      - name: plan
        run: |
          cd tf
          nix develop --command tofu plan -detailed-exitcode -out tfplan  || export exitcode=$?
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          if [ $exitcode -eq 1 ]; then
            exit 1
          else 
            exit 0
          fi
      - name: publish plan
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4
        with:
          name: tfplan
          path: tfplan

  deploy:
    runs-on: ubuntu-latest
    environment: infra
    steps:
      - name: init
        run: |
          cd tf
          nix develop --command ./tofu-init.sh
      - name: apply
        run: |
          cd tf
          nix develop --command tofu apply

